### PR TITLE
Addressing the `.mongooseTypeOptions/.mongoose is not a function`

### PR DESCRIPTION
**Pull request by Harm-Nullix**
The error is caused because the `z.ZObject` prototype is extended

Because is some cases there can be multiple imports of `z` it is impossible to tell if the right prototype is extended. It is a bad practice because you have no control over the `z` object as an user of this library.

That is why:
* We created a wrapper for the extension function to pass down your own z object
* We expose the specific extended z object

We created some tests and updated the docs accordingly.

[x] `npm run test`
[x] `npm run lint`
[x] linked issue #2 

Kind regards

### CODE REVIEW

**Comment by andreww2012** [comment]
Thank you very much for the first PR! 😊 This all does make sense.

As a continuation to the proposed changes, I just thought that it would also be good to have a `setup` function that would allow setting a custom `z` (or requesting to not pollute the prototype altogether), and also setting the global default schema options (like `disablePlugins: true` for every schema).

**Comment by MarijnMensinga** [comment]
@andreww2012 I think that is a very good proposal because due too the prototype polution it is currently not possible to use the [h3-zod ](https://www.npmjs.com/package/h3-zod) out of the box with mongoose-zod:

```javascript
import { useValidatedBody } from 'h3-zod'
import { toZodMongooseSchema } from 'mongoose-zod'

export const zodMongooseSchema = toZodMongooseSchema(
  z.object({
    nameFirst: z.string().min(5).max(200),
  })
)

...

export default defineEventHandler((event) => {
    const body = await useValidatedBody(event, zodMongooseSchema). <== triggers error
}
```

This can of course be fixed by exporting the z object itself before inserting it into `toZodMongooseSchema` but it would be nice to not have to worry about this.

This works:
```javascript
import { useValidatedBody } from 'h3-zod'
import { toZodMongooseSchema } from 'mongoose-zod'

export const zodSchema = z.object({
    nameFirst: z.string().min(5).max(200),
  })
export const zodMongooseSchema = toZodMongooseSchema(zodSchema)

...

export default defineEventHandler((event) => {
    const body = await useValidatedBody(event, zodSchema). <== this works
}
```

**Comment by andreww2012** [comment]
@MarijnMensinga I don't think this is related to prototype extension, because `z.ZodObject.prototype.mongoose()` returns `ZodMongoose` instance which of course incompatible with likely the object type expected by `useValidatedBody`. So even if you had used `.mongoose()` in your second example instead of `toZodMongooseSchema`, `mongoose-zod` would not have altered the original zod schema.

Either way, you can now opt out of zod prototype extension in 0.1.1. 😋

**Comment by MarijnMensinga** [comment]
@andreww2012 you're right! tested it this morning and saw this as well. Either way it's nice to have the option of a clean ZodObject.
