### ISSUE TITLE
Addressing I get the error: `.mongooseTypeOptions/.mongoose is not a function`

### ISSUE THREAD

**Issue by Harm-Nullix** [andreww2012/mongoose-zod#2]
The error is caused because the z.ZObject prototype is extended

Because is some cases there can be multiple imports of z it is impossible to tell if the right prototype is extended. It is a bad practice because you have no control over the z object as an user of this library.

It would be useful if the z object of mongoose-zod is exposed or we can pass a zObject by reference instead of extending the prototype

**Comment by MarijnMensinga** [comment]
+1
